### ISSUE TITLE
Ruin

### ISSUE THREAD

**Issue by ShadoW2551** [Shieldowskyy/spolszczenie-fnaf-sb#5]
Dobrą robotę odwaliłeś z podstawką ;)
Zamierzasz również inne gry tłumaczyć?

**Comment by Shieldowskyy** [comment]
Spolszczenie do Ruin będzie na dniach. Podstawka również dostanie poprawioną wersję ;)

**Comment by Shieldowskyy** [comment]
@ShadoW2551 Spolszczenie do RUIN już jest dostępne do otwartych testów!
